### ISSUE TITLE
Sideways Arrows

### ISSUE THREAD

**Issue by citrusspoon** [Bananapen/Adv-Game-Design#45] opened 2017-01-21 19:30 UTC
I don't know if this is something only manifesting for me, but when I shoot the arrows they shoot sideways. Like the model is rotated 90 degrees. Is this an easy correction?

**Comment by Byroni** [comment] 2017-01-22 01:21
Yah it's like that for me too. I opened an issue to fix that later on.

**Comment by LupinWonse** [comment] 2017-01-23 15:42
I am closing this issue as it is a duplicate of #22

**Closed by LupinWonse** 2017-01-23 15:42 UTC
Labels: help wanted
